name: 同步上游仓库
on:
  schedule:
    - cron: '0 0-16/4 * * *'
  workflow_dispatch:
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: 同步上游仓库
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/tnanko2019/xmly_speed.git"
          source_branch: "master"
          destination_branch: "main"
          github_token: ${{ secrets.PAT }}

          
      - name: Merge main -> master	
        uses: devmasx/merge-branch@v1.3.1	
        if: env.PAT	
        with:	
          type: now	
          from_branch: main	
          target_branch: master	
          github_token: ${{ secrets.PAT }}

      
